name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Create test account
      run: |
        curl -X DELETE "https://automationexercise.com/api/deleteAccount" \
          -d "email=jacobmotsweni18@gmail.com&password=Langa@24"
        curl -X POST "https://automationexercise.com/api/createAccount" \
          -d "name=Jacob Motsweni&email=jacobmotsweni18@gmail.com&password=Langa@24&title=Mr&birth_date=5&birth_month=June&birth_year=1993&firstname=Jacob&lastname=Motsweni&company=Test Company&address1=123 Main Street&address2=Apartment 1&country=South Africa&zipcode=2000&state=Gauteng&city=Johannesburg&mobile_number=0649546712"
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30